/ Mock user bids data
const myBids = [
  {
    id: 1,
    eventId: "corporate-gala",
    eventName: "Annual Corporate Gala",
    eventDate: new Date(new Date().setDate(new Date().getDate() + 30)),
    eventImage: "/placeholder.svg?height=200&width=300&text=Corporate+Gala",
    bidAmount: 7500,
    bidTime: new Date(new Date().setHours(new Date().getHours() - 5)),
    currentBid: 7500,
    biddingEndsAt: new Date(new Date().setDate(new Date().getDate() + 15)),
    status: "highest", // highest, outbid, won, lost, paid
    startingPrice: 5000,
    endingPrice: 15000,
    depositPaid: false,
  },
  {
    id: 2,
    eventId: "wedding-venue",
    eventName: "Luxury Wedding Venue",
    eventDate: new Date(new Date().setDate(new Date().getDate() + 60)),
    eventImage: "/placeholder.svg?height=200&width=300&text=Wedding+Venue",
    bidAmount: 14500,
    bidTime: new Date(new Date().setHours(new Date().getHours() - 10)),
    currentBid: 15000,
    biddingEndsAt: new Date(new Date().setDate(new Date().getDate() + 20)),
    status: "outbid",
    startingPrice: 10000,
    endingPrice: 25000,
    depositPaid: false,
  },
  {
    id: 3,
    eventId: "tech-conference",
    eventName: "Tech Conference Hall",
    eventDate: new Date(new Date().setDate(new Date().getDate() - 15)),
    eventImage: "/placeholder.svg?height=200&width=300&text=Conference+Hall",
    bidAmount: 11500,
    bidTime: new Date(new Date().setDate(new Date().getDate() - 25)),
    currentBid: 12000,
    biddingEndsAt: new Date(new Date().setDate(new Date().getDate() - 20)),
    status: "lost",
    startingPrice: 8000,
    endingPrice: 20000,
    depositPaid: false,
  },
  {
    id: 4,
    eventId: "charity-gala",
    eventName: "Charity Fundraiser Venue",
    eventDate: new Date(new Date().setDate(new Date().getDate() - 5)),
    eventImage: "/placeholder.svg?height=200&width=300&text=Charity+Gala",
    bidAmount: 9800,
    bidTime: new Date(new Date().setDate(new Date().getDate() - 15)),
    currentBid: 9800,
    biddingEndsAt: new Date(new Date().setDate(new Date().getDate() - 10)),
    status: "won",
    startingPrice: 7000,
    endingPrice: 18000,
    depositPaid: false,
  },
  {
    id: 5,
    eventId: "art-exhibition",
    eventName: "Art Exhibition Space",
    eventDate: new Date(new Date().setDate(new Date().getDate() + 45)),
    eventImage: "/placeholder.svg?height=200&width=300&text=Art+Exhibition",
    bidAmount: 8500,
    bidTime: new Date(new Date().setDate(new Date().getDate() - 12)),
    currentBid: 8500,
    biddingEndsAt: new Date(new Date().setDate(new Date().getDate() - 8)),
    status: "paid",
    startingPrice: 6000,
    endingPrice: 15000,
    depositPaid: true,
    paymentDate: new Date(new Date().setDate(new Date().getDate() - 7)),
  },
]



const events = {
  "corporate-gala": {
    id: "corporate-gala",
    name: "Annual Corporate Gala",
    description:
      "An exclusive evening of networking, fine dining, and entertainment for corporate executives and business leaders.",
    longDescription:
      "Join us for our prestigious Annual Corporate Gala, a premier networking event designed for executives and business leaders. This exclusive evening features gourmet dining, live entertainment, and opportunities to connect with industry influencers. The elegant venue provides the perfect backdrop for meaningful conversations and potential partnerships. Our carefully curated program includes keynote speeches from thought leaders, recognition of business achievements, and entertainment that will make this night memorable.",
    date: new Date(new Date().setDate(new Date().getDate() + 30)),
    time: "7:00 PM - 11:00 PM",
    location: "Grand Ballroom, Luxury Hotel, 123 Main Street, New York, NY",
    capacity: 200,
    organizer: "Business Network Association",
    startingPrice: 5000,
    endingPrice: 15000,
    currentBid: 7500,
    biddingEndsAt: new Date(new Date().setDate(new Date().getDate() + 15)),
    images: [
      "/placeholder.svg?height=600&width=800&text=Corporate+Gala",
      "/placeholder.svg?height=600&width=800&text=Gala+Dining",
      "/placeholder.svg?height=600&width=800&text=Gala+Entertainment",
      "/placeholder.svg?height=600&width=800&text=Gala+Networking",
    ],
    features: [
      "Exclusive networking with industry leaders",
      "Gourmet 5-course dinner with premium beverages",
      "Live entertainment and music",
      "Professional photography",
      "Valet parking for all guests",
    ],
    agenda: [
      { time: "7:00 PM - 7:45 PM", activity: "Welcome Reception & Cocktails" },
      { time: "7:45 PM - 8:00 PM", activity: "Opening Remarks" },
      { time: "8:00 PM - 9:30 PM", activity: "Gourmet Dinner Service" },
      { time: "9:30 PM - 10:00 PM", activity: "Keynote Speaker" },
      { time: "10:00 PM - 11:00 PM", activity: "Networking & Entertainment" },
    ],
    bids: [
      {
        id: 1,
        userId: "user1",
        userName: "John Smith",
        amount: 7500,
        time: new Date(new Date().setHours(new Date().getHours() - 5)),
        status: "highest",
      },
      {
        id: 2,
        userId: "user2",
        userName: "Emily Johnson",
        amount: 7200,
        time: new Date(new Date().setHours(new Date().getHours() - 8)),
        status: "outbid",
      },
      {
        id: 3,
        userId: "user3",
        userName: "Michael Brown",
        amount: 6800,
        time: new Date(new Date().setHours(new Date().getHours() - 12)),
        status: "outbid",
      },
      {
        id: 4,
        userId: "user4",
        userName: "Sarah Davis",
        amount: 6500,
        time: new Date(new Date().setHours(new Date().getHours() - 18)),
        status: "outbid",
      },
      {
        id: 5,
        userId: "user5",
        userName: "Robert Wilson",
        amount: 6000,
        time: new Date(new Date().setHours(new Date().getHours() - 24)),
        status: "outbid",
      },
    ],
  },
  "wedding-venue": {
    id: "wedding-venue",
    name: "Luxury Wedding Venue",
    description:
      "A stunning venue for your dream wedding, featuring beautiful gardens, elegant ballroom, and premium catering services.",
    longDescription:
      "Make your special day truly unforgettable at our Luxury Wedding Venue. This picturesque location offers breathtaking views, meticulously maintained gardens, and an elegant ballroom that can be customized to your vision. Our comprehensive wedding package includes premium catering services, professional event coordination, and state-of-the-art sound and lighting systems. The venue's versatile spaces can accommodate both intimate gatherings and grand celebrations, with indoor and outdoor options available for your ceremony and reception.",
    date: new Date(new Date().setDate(new Date().getDate() + 60)),
    time: "Flexible",
    location: "Riverside Estate, 456 Garden Road, Los Angeles, CA",
    capacity: 150,
    organizer: "Luxury Venues Inc.",
    startingPrice: 10000,
    endingPrice: 25000,
    currentBid: 15000,
    biddingEndsAt: new Date(new Date().setDate(new Date().getDate() + 20)),
    images: [
      "/placeholder.svg?height=600&width=800&text=Wedding+Venue",
      "/placeholder.svg?height=600&width=800&text=Wedding+Garden",
      "/placeholder.svg?height=600&width=800&text=Wedding+Ballroom",
      "/placeholder.svg?height=600&width=800&text=Wedding+Dining",
    ],
    features: [
      "Exclusive use of the entire venue for your wedding day",
      "Professional wedding coordinator",
      "Premium catering package with customizable menu",
      "Bridal suite and groom's room",
      "State-of-the-art sound and lighting systems",
    ],
    agenda: [
      { time: "Flexible", activity: "Ceremony in Garden or Ballroom" },
      { time: "Flexible", activity: "Cocktail Hour" },
      { time: "Flexible", activity: "Reception and Dinner" },
      { time: "Flexible", activity: "Dancing and Entertainment" },
      { time: "Flexible", activity: "Late Night Snacks and Farewell" },
    ],
    bids: [
      {
        id: 1,
        userId: "user6",
        userName: "Jennifer Adams",
        amount: 15000,
        time: new Date(new Date().setHours(new Date().getHours() - 3)),
        status: "highest",
      },
      {
        id: 2,
        userId: "user7",
        userName: "David Miller",
        amount: 14500,
        time: new Date(new Date().setHours(new Date().getHours() - 10)),
        status: "outbid",
      },
      {
        id: 3,
        userId: "user8",
        userName: "Lisa Taylor",
        amount: 13800,
        time: new Date(new Date().setHours(new Date().getHours() - 15)),
        status: "outbid",
      },
      {
        id: 4,
        userId: "user9",
        userName: "James Wilson",
        amount: 12500,
        time: new Date(new Date().setHours(new Date().getHours() - 20)),
        status: "outbid",
      },
      {
        id: 5,
        userId: "user10",
        userName: "Amanda Clark",
        amount: 11000,
        time: new Date(new Date().setHours(new Date().getHours() - 30)),
        status: "outbid",
      },
    ],
  },
  "conference-hall": {
    id: "conference-hall",
    name: "Tech Conference Hall",
    description:
      "A modern conference facility with cutting-edge technology, perfect for tech events, product launches, and industry conferences.",
    longDescription:
      "Host your next tech event, product launch, or industry conference at our state-of-the-art Tech Conference Hall. This modern facility features cutting-edge audiovisual equipment, high-speed internet, and flexible spaces that can be configured to your specific needs. From intimate breakout sessions to large keynote presentations, our venue can accommodate various formats and audience sizes. The dedicated technical staff ensures seamless execution of your event, while our central location and ample parking make it convenient for all attendees.",
    date: new Date(new Date().setDate(new Date().getDate() + 45)),
    time: "8:00 AM - 6:00 PM",
    location: "Innovation Center, 789 Tech Boulevard, San Francisco, CA",
    capacity: 500,
    organizer: "TechVenues Co.",
    startingPrice: 8000,
    endingPrice: 20000,
    currentBid: 12000,
    biddingEndsAt: new Date(new Date().setDate(new Date().getDate() + 10)),
    images: [
      "/placeholder.svg?height=600&width=800&text=Conference+Hall",
      "/placeholder.svg?height=600&width=800&text=Conference+Stage",
      "/placeholder.svg?height=600&width=800&text=Conference+Seating",
      "/placeholder.svg?height=600&width=800&text=Conference+Tech",
    ],
    features: [
      "State-of-the-art audiovisual equipment",
      "High-speed internet for all attendees",
      "Multiple breakout rooms",
      "Dedicated technical support staff",
      "Catering options available",
    ],
    agenda: [
      { time: "8:00 AM - 9:00 AM", activity: "Registration and Breakfast" },
      { time: "9:00 AM - 12:00 PM", activity: "Morning Sessions" },
      { time: "12:00 PM - 1:00 PM", activity: "Lunch Break" },
      { time: "1:00 PM - 5:00 PM", activity: "Afternoon Sessions" },
      { time: "5:00 PM - 6:00 PM", activity: "Networking Reception" },
    ],
    bids: [
      {
        id: 1,
        userId: "user11",
        userName: "Thomas Chen",
        amount: 12000,
        time: new Date(new Date().setHours(new Date().getHours() - 2)),
        status: "highest",
      },
      {
        id: 2,
        userId: "user12",
        userName: "Sophia Rodriguez",
        amount: 11500,
        time: new Date(new Date().setHours(new Date().getHours() - 6)),
        status: "outbid",
      },
      {
        id: 3,
        userId: "user13",
        userName: "Daniel Kim",
        amount: 10800,
        time: new Date(new Date().setHours(new Date().getHours() - 14)),
        status: "outbid",
      },
      {
        id: 4,
        userId: "user14",
        userName: "Olivia Martinez",
        amount: 10000,
        time: new Date(new Date().setHours(new Date().getHours() - 22)),
        status: "outbid",
      },
      {
        id: 5,
        userId: "user15",
        userName: "William Johnson",
        amount: 9000,
        time: new Date(new Date().setHours(new Date().getHours() - 36)),
        status: "outbid",
      },
    ],
  },
}
