export const events = [
    {
      id: "evt_001",
      eventName: "Rock Guitar Concert",
      price: 999,
      description: "Join us for an electrifying night with the best rock guitarists in the country. Experience live music like never before!",
      imageUrl: "/event1.jpg",
      videoUrl: "/videos/rock-concert.mp4",
      userId: "user_123",
      createdAt: "2025-03-07",
      eventType: "Music",
    },
    {
      id: "evt_002",
      eventName: "Classical Symphony Night",
      price: 1299,
      description: "An evening of classical symphony with renowned orchestras performing timeless compositions.",
      imageUrl: "/event2.jpg",
      videoUrl: "/videos/classical-symphony.mp4",
      userId: "user_456",
      createdAt: "2025-03-06",
      eventType: "Music",
    },
    {
      id: "evt_003",
      eventName: "Jazz & Blues Festival",
      price: 1499,
      description: "A mesmerizing jazz and blues event featuring top artists, soulful performances, and a magical atmosphere.",
      imageUrl: "/event3.jpg",
      videoUrl: "/videos/jazz-festival.mp4",
      userId: "user_789",
      createdAt: "2025-03-05",
      eventType: "Music",
    },
    {
      id: "evt_004",
      eventName: "Bollywood Night Extravaganza",
      price: 899,
      description: "Get ready for a Bollywood-themed night filled with music, dance, and live performances by famous playback singers.",
      imageUrl: "/event4.jpg",
      videoUrl: "/videos/bollywood-night.mp4",
      userId: "user_101",
      createdAt: "2025-03-04",
      eventType: "Entertainment",
    },
    {
      id: "evt_005",
      eventName: "EDM Music Festival",
      price: 1599,
      description: "Experience the ultimate EDM festival with world-famous DJs, stunning visuals, and a crowd full of energy.",
      imageUrl: "/event5.jpg",
      videoUrl: "/videos/edm-festival.mp4",
      userId: "user_202",
      createdAt: "2025-03-03",
      eventType: "Music",
    },
  ];
  